### ISSUE TITLE
Websocket diff payload size is dramatically large

### ISSUE THREAD

**Issue by miickel** [msaraiva/surface#254] opened 2021-01-19 09:36 UTC
Hi,

Thanks for your great work on this library!

I have this fairly simple component that represents a page in my app:

```elixir
defmodule TalkyWeb.Components.PodcastDetailsPage do
  use Surface.Component

  alias Surface.Components.Form.{Field, Label, Checkbox}
  alias Surface.Components.Form

  prop podcast, :map, required: true
  prop change, :event, required: true

  @impl true
  def render(assigns) do
    ~H"""
    <h2>{{ @podcast.title }}</h2>
    <p>{{ @podcast.description }}</p>

    <h3>Episodes</h3>
    <ul>
      <li :for={{ episode <- @podcast.episodes }}>
        {{ episode.title }}
      </li>
    </ul>

    <h3>Feeds</h3>
    <ul>
      <li :for={{ feed <- @podcast.feeds }}>
        {{ feed.title || feed.url }}
      </li>
    </ul>

    <Form for={{:podcast}} change={{@change}}>
      <Field name="is_feed_public">
        <Label />
        <Checkbox opts={{[checked: @podcast.is_feed_public]}} />
      </Field>
    </Form>
    """
  end
end
```

This is used by the parent `Surface.LiveView`, like this:

```elixir
defmodule TalkyWeb.PodcastLive do
  use Surface.LiveView

  alias TalkyWeb.Components.PodcastDetailsPage
  alias Talky.Feeds

  data podcast, :map, default: nil

  @impl true
  def mount(%{"podcast_id" => podcast_id}, %{"user_token" => user_token}, socket) do
    if connected?(socket), do: Feeds.subscribe_podcast(podcast_id)

    user = user_token && Talky.Accounts.get_user_by_session_token(user_token)

    socket =
      socket
      |> assign(:current_user, user)
      |> assign_podcast(podcast_id)

    {:ok, socket}
  end

  def assign_podcast(socket, podcast_id) do
    podcast = Talky.Feeds.get_own_podcast_details(socket.assigns.current_user, podcast_id)
    assign(socket, :podcast, podcast)
  end

  @impl true
  def render(assigns) do
    ~H"""
    <PodcastDetailsPage
    :if={{@podcast}}
    podcast={{@podcast}}
    change="podcast_change"
    />
    """
  end

  @impl true
  def handle_event("podcast_change", %{"podcast" => params}, socket) do
    Feeds.update_podcast(socket.assigns.podcast, %{
      is_feed_public: params["is_feed_public"]
    })

    {:noreply, socket}
  end

  @impl true
  def handle_info({Feeds, [:podcast, :updated], podcast}, socket) do
    socket = assign(socket, :podcast, podcast)
    {:noreply, socket}
  end
end

```

In `handle_event/3` a single boolean prop gets toggled on the Podcast struct stored in socket.assigns. The update is then broadcasted and `handle_info/3` replace `socket.assigns.podcast` with the updated struct.

While this technically works, the payload sent over the wire is very much larger than I'd expect. The full struct is sent each time I toggle the checkbox, as well as the full static template.

I looked at the Surface docs/demos for clues, but found the same issue there (I guess). Take a look at [Built-in Components/Form](http://surface-demo.msaraiva.io/builtincomponents/Form) to get a feel for the issue.

Typing name "John Doe" and email "john@doe.com", the following payload is sent over the socket:

```json
[
  "113",
  "159",
  "lv:FormInfo",
  "phx_reply",
  {
    "response": {
      "diff": {
        "0": {
          "0": " id=\"ComponentInfo_Form\"",
          "3": "Form",
          "4": "<div class=\"subtitle\"><p>\nDefines a <strong>form</strong> that lets the user submit information</p>\n</div>",
          "5": "",
          "6": "<div class=\"content\"><p>\nProvides a wrapper for <code class=\"inline\">Phoenix.HTML.Form.form_for/3</code>. Additionally,\nadds the form instance that is returned by <code class=\"inline\">form_for/3</code> into the context,\nmaking it available to any child input.</p>\n<p>\nAll options passed via <code class=\"inline\">opts</code> will be sent to <code class=\"inline\">form_for/3</code>, <code class=\"inline\">for</code>\nand <code class=\"inline\">action</code> can be set directly and will override anything in <code class=\"inline\">opts</code>.</p>\n</div>",
          "7": {
            "1": {
              "0": {
                "0": "<form action=\"#\" autocomplete=\"off\" method=\"post\" phx-change=\"change\"><input name=\"_csrf_token\" type=\"hidden\" value=\"DXsyJSszDmdmDRErHARYTgstIDx1ARE0lHJIQZk3SaemSu0vfTVyXXTv\">",
                "1": {
                  "0": {
                    "0": {
                      "0": {
                        "0": " class=\"field\"",
                        "1": {
                          "0": {
                            "0": {
                              "0": {
                                "0": {
                                  "0": {
                                    "0": {
                                      "0": {
                                        "0": "<label class=\"label\" for=\"user_name\">Name</label>"
                                      }
                                    }
                                  }
                                }
                              },
                              "1": " class=\"control\"",
                              "2": {
                                "0": {
                                  "0": {
                                    "0": {
                                      "0": {
                                        "0": "<input class=\"input\" id=\"user_name\" name=\"user[name]\" type=\"text\" value=\"John Doe\">"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "1": {
                        "0": " class=\"field\"",
                        "1": {
                          "0": {
                            "0": {
                              "0": {
                                "0": {
                                  "0": {
                                    "0": {
                                      "0": {
                                        "0": "<label class=\"label\" for=\"user_email\">E-mail</label>"
                                      }
                                    }
                                  }
                                }
                              },
                              "1": " class=\"control\"",
                              "2": {
                                "0": {
                                  "0": {
                                    "0": {
                                      "0": {
                                        "0": "<input class=\"input\" id=\"user_email\" name=\"user[email]\" type=\"text\" value=\"john@doe.com\">"
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              },
              "1": "{\n  &quot;email&quot;: &quot;john@doe.com&quot;,\n  &quot;name&quot;: &quot;John Doe&quot;\n}"
            }
          },
          "9": 1,
          "10": {
            "2": {
              "0": 2
            }
          }
        }
      }
    },
    "status": "ok"
  }
]
```

Perhaps this works as expected, but I thought the LiveView diffing used under the hood was smarter than this?

I'm new to both Phoenix and LiveView.

**Comment by dvic** [comment] 2021-01-19 11:07
Hmm, does it make any difference if you use a stateful component (i.e., `use Surface.LiveComponent` and add an `id`)

**Comment by lnr0626** [comment] 2021-01-19 15:17
I converted the code you posted to just plain live view (it's not exact, but it's pretty close: https://github.com/lnr0626/large_diff_payload_web). When I click the checkbox, the diff sent across the wire is:

```json
[
    "4",
    "5",
    "lv:phx-FluoWewwsTVidQUD",
    "phx_reply",
    {
        "response": {
            "diff": {
                "2": {
                    "0": {
                        "0": {
                            "0": "The one true podcast pfnY",
                            "1": "Some text about the pod cast....but wait, there&#39;s some randomness!! KgeqxMgNLANssHcvDgdnVPOxTVnrefyUsatCam",
                            "2": {
                                "d": [
                                    [
                                        "Episode Name UoeTCyExsv"
                                    ],
                                    [
                                        "Episode Name kRMDdbRODl"
                                    ],
                                    [
                                        "Episode Name rnVwWU US"
                                    ],
                                    [
                                        "Episode Name UWoKIIbIJg"
                                    ],
                                    [
                                        "Episode Name zTukPxqXP"
                                    ],
                                    [
                                        "Episode Name XBRTReshF"
                                    ],
                                    [
                                        "Episode Name IZbRUrpmk"
                                    ],
                                    [
                                        "Episode Name fmTCrjNltI"
                                    ]
                                ]
                            },
                            "3": {
                                "d": [
                                    [
                                        "Feed Name KWQkSQPpoy"
                                    ],
                                    [
                                        "Feed Name aPYIXwaa"
                                    ]
                                ]
                            },
                            "4": "<form action=\"#\" method=\"post\" phx-change=\"podcast_change\"><input name=\"_csrf_token\" type=\"hidden\" value=\"PCF9RwJ0CxokOQQ9HwNoOXhsAURiKBs2wND-HCGBi_uSmJ-UN3H-PQPi\">",
                            "5": "<label for=\"podcast_is_feed_public\">Is feed public</label>",
                            "6": "<input name=\"podcast[is_feed_public]\" type=\"hidden\" value=\"false\"><input checked=\"true\" id=\"podcast_is_feed_public\" name=\"podcast[is_feed_public]\" type=\"checkbox\" value=\"true\">"
                        }
                    }
                }
            }
        },
        "status": "ok"
    }
]
```

There are some slight differences because I didn't do any styling (so no `class="..."` diffs), but the size/content is fairly comparable.

I also added an example using a live component, which resulted in the following diff when the checkbox was checked:

```json
[
    "4",
    "5",
    "lv:phx-Fluq4XRTiDhPQgJk",
    "phx_reply",
    {
        "response": {
            "diff": {
                "2": {
                    "1": {
                        "0": 1
                    }
                },
                "c": {
                    "1": {
                        "4": "<form action=\"#\" method=\"post\" phx-change=\"podcast_2_change\"><input name=\"_csrf_token\" type=\"hidden\" value=\"fSRVWx1eHQt7KEc-QSNzKnMsDTBZGiku6Kl1WiQS6N6P3j6FEsDYkcbq\">",
                        "5": "<label for=\"podcast_is_feed_public\">Is feed public</label>",
                        "6": "<input name=\"podcast[is_feed_public]\" type=\"hidden\" value=\"false\"><input checked=\"true\" id=\"podcast_is_feed_public\" name=\"podcast[is_feed_public]\" type=\"checkbox\" value=\"true\">"
                    }
                }
            }
        },
        "status": "ok"
    }
]
```

the demo site uses some stuff to avoid duplicating code between the examples and demos of the example, so the diffs on those may not be as optimized as the could be

@msaraiva may have some addition insight as he's more familiar with how the change tracking works

**Comment by miickel** [comment] 2021-01-19 18:06
Using a stateful component the payload size changes from ~900 to ~600 bytes. The whole form markup is still sent with each toggle of the checkbox.

@Inr0626 interesting, that seems to have improved it by quite a bit. I still don't understand why the markup is sent with each change, though.

**Comment by msaraiva** [comment] 2021-01-20 12:31
Hey @miickel!

As already mentioned, change tracking has its limitations. As far as I can remember, change tracking is disabled inside functions like `form_for` and any other helper function depending on `content_tag`. That's actually the only reason we don't care much about passing `assigns` to helper functions inside form controls. We'd probably need to run some additional tests to confirm that but based on the results of @lnr0626's experiments, I'd say that that assumption is correct. 

I believe this could be addressed (or at least improved) when LV introduces the new functional component which might replace those helper functions allowing change tracking.

In case you want to run some extra benchmarks to make sure, I'd advise following @lnr0626 steps and try to create a minimal example in plain LV. If the issue is not present then we may have a way to optimize it on the Surface side.

I'm closing this issue for now but feel free to reopen it in case you have any update.

Thanks for the provided example and the detailed explanation.

**Closed by msaraiva** 2021-01-20 12:31 UTC
