### ISSUE TITLE
Unable to nest a stateful component inside a Form

### ISSUE THREAD

**Issue by brainlid** [msaraiva/surface#10] opened 2019-12-16 20:55 UTC
I am unable to nest a stateful component inside a Form component. Perhaps there is something additional needed in the setup of the Form? 

It results in this error:

```
[error] GenServer #PID<0.1987.0> terminating
** (ArgumentError) cannot convert component FeWeb.Editor.Inspectors.Components.LiveOptions with id "live-options" to HTML. A component must always be returned directly as part of a LiveView template
```

Here is the context that they are being rendered in:

```elixir
defmodule FeWeb.Editor.InspectorPane do
  use Surface.LiveComponent

  alias FeWeb.Editor.Inspectors.Components.Form
  alias FeWeb.Editor.Inspectors.Components.LiveOptions

  def render(assigns) do
    ~H"""
    <div id="inspector_pane">
      <Form for={{ @changeset }} id="inspector_form" as="inspector_form" change="validate_inspector" autocomplete="off">
        <LiveOptions id="live-options" />
      </Form>
    </div>
    """
  end
```

In the above example, moving the "LiveOptions" component **outside** of the Form works.

Below is the code for the "stateful" item being nested. It manages no state, but it is a "Surface.LiveComponent". Changing it to a "Surface.Component" works fine.

```elixir
defmodule FeWeb.Editor.Inspectors.Components.LiveOptions do
  use Surface.LiveComponent

  @doc """
  Render the options live component for the inspector.
  """
  def render(assigns) do
    IO.puts "11111111111111111111111111111111111"
    IO.puts "11111111111111111111111111111111111"
    IO.puts "11111111111111111111111111111111111"
    ~H"""
    <p>Testing</p>
    """
  end
end
```

The "Form" component is heavily based on yours. For completeness the code follows. I assume that the Form component needs to be stateful. It appears that in order for a stateful component to be used, the entire hierarchy above it must be stateful as well. Is that correct?

```elixir
defmodule FeWeb.Editor.Inspectors.Components.Form do
  @moduledoc """
  A surface "Form" component used for the inspector.
  """
  use Surface.LiveComponent

  import Phoenix.HTML.Form

  property for, :string, required: true
  property as, :string
  property change, :event
  property submit, :event
  property autocomplete, :string

  def begin_context(props) do
    form =
      form_for(props.for, "#",
        as: props.as,
        novalidate: true,
        phx_submit: props.submit,
        phx_change: props.change,
        autocomplete: props.autocomplete
      )

    Map.put(props.context, :form, form)
  end

  def render(assigns) do
    ~H"""
    {{ @context.form }}
      {{ @inner_content.() }}
    {{ raw("</form>") }}
    """
  end

  def end_context(props) do
    Map.delete(props.context, :form)
  end
end
```

**Comment by msaraiva** [comment] 2019-12-17 14:09
> I assume that the Form component needs to be stateful. It appears that in order for a stateful component to be used, the entire hierarchy above it must be stateful as well. Is that correct?

Maybe. We need to investigate if Phoenix can only keep track of the state if you always use `live_component/3`. If that's the case, then this is true since `Surface.Component` does not use it. If this is by design, we have 3 options:

  1. Document that this is the default behaviour and tell the user that he'll always need to use `Surface.LiveComponent` for that.
  1. Refactor `Surface.Component` to also use `live_component/3`. In this case,  we'll not be able to use components in stateless non-LiveView applications.
  1. Add a `component/3` function to Phoenix core that could be used to define stateless components that do not depend on LiveView but enable LiveView to keep track of the state. The problem here is that I'm not sure this is feasible nor desired by the Phoenix core team.

**Comment by msaraiva** [comment] 2019-12-17 14:15
BTW, I think the third one would be the best option, unfortunately, it's the only one that doesn't depend on me :(

**Comment by Zurga** [comment] 2019-12-27 18:58
> I assume that the Form component needs to be stateful. It appears that in order for a stateful component to be used, the entire hierarchy above it must be stateful as well. Is that correct?

I have tried stateful components in the entire hierarchy and can't get it to work.

It seems the problem is in the @inner_content.() function call. The error comes from ```phoenix_live_view/engine.ex``` at line 22.

**Comment by brainlid** [comment] 2019-12-30 20:46
Just to be clear, and re-confirming what @Zurga said, putting the following component inside a `<Form>` component breaks with the following stacktrace.

```elixir
defmodule TestingLiveComp do
  use Surface.LiveComponent

  def render(assigns) do
    IO.inspect assigns, label: "LIVE COMP"

    ~H"""
    <div class="hero">
    Testing
    </div>
    """
  end
end
```

```
[error] GenServer #PID<0.3706.0> terminating
** (ArgumentError) cannot convert component FeWeb.Editor.Inspectors.TestingLiveComp with id "testing" to HTML. A component must always be returned directly as part of a LiveView template
    (phoenix_live_view) lib/phoenix_live_view/engine.ex:20: Phoenix.HTML.Safe.Phoenix.LiveView.Component.to_iodata/1
    (fe_web) lib/fe_web/views/editor/inspector_pane.ex:60: anonymous fn/2 in FeWeb.Editor.InspectorPane.render/1
    (fe_web) lib/fe_web/views/editor/inspectors/components/form.ex:32: FeWeb.Editor.Inspectors.Components.Form.render/1
    (phoenix_live_view) lib/phoenix_live_view/utils.ex:67: Phoenix.LiveView.Utils.to_rendered/2
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:426: Phoenix.LiveView.Diff.render_component/7
    (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib) maps.erl:232: :maps.fold_1/3
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:369: Phoenix.LiveView.Diff.render_pending_components/4
    (phoenix_live_view) lib/phoenix_live_view/diff.ex:86: Phoenix.LiveView.Diff.render/3
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:440: Phoenix.LiveView.Channel.render_diff/2
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:339: Phoenix.LiveView.Channel.handle_changed/4
    (phoenix_live_view) lib/phoenix_live_view/channel.ex:223: Phoenix.LiveView.Channel.handle_result/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I believe the problem is in this line...

```
lib/fe_web/views/editor/inspectors/components/form.ex:32: FeWeb.Editor.Inspectors.Components.Form.render/1
```

Which corresponds to the Form's **@inner_content.()** line:

```elixir
  def render(assigns) do
    ~H"""
    {{ @context.form }}
      {{ @inner_content.() }}
    <#Raw></form></#Raw>
    """
  end
```

When the component is moved outside of the form and made a sibling, it renders as expected.

The problem appears to be around the "Form" idea and how contexts work or something. I admit I don't understand how "inner_content" is used.

**Comment by msaraiva** [comment] 2019-12-30 21:06
@brainlid and @Zurga thanks a bunch for the detailed report. I'll try to address this in the morning. Just to confirm, if you change the implementation of the `Form` to use `Surface.LiveComponent` instead of `Surface.Component`, do you still get the error? As far as I could understand, you don't. Right?

This is important because if the problem only happens with `Surface.Component`, we probably going to need changes in LV to support it. Otherwise, we'll need to drop support for the stateless non-liveview component.

**Comment by brainlid** [comment] 2019-12-30 21:09
I have tested when the Form is a `Surface.LiveComponent` and a `Surface.Component`.  The stacktraces appear to be the same.

**Comment by msaraiva** [comment] 2019-12-30 21:18
This is good news in some way. That means we can fix it without changing LiveView. On the other hand, it means the implementation of `Surface.Component` is gonna get more complex since we'll need to have two different implementations that have to be switched according to the presence or not of LiveView as a dependency. The other, much simpler option as I said, is dropping support for `Surface.Component`. In this case, LiveView will become a hard dependency.

**Comment by brainlid** [comment] 2019-12-30 21:52
After doing more with LiveView and Surface, here are some updated thoughts. Initially we thought it would be really valuable for a component to be used in an EEX template as well as a LiveView page (meaning for server-side rendered pages only -- not live view). Now we see fewer scenarios where that would be a choice we would make. However, if we had more public facing pages (ie not logged in), like a blog or a marketing website, then it might be preferable to avoid creating and holding open a websocket connection to that client.

So, speaking for myself and my usage, I would be fine with it always being used in the context of a LiveView page.

When you say dropping support for `Surface.Component`, does that mean dropping support for stateless components too? Because we use stateless components as much as possible as they are easier to use and test. I really like stateless components. But I'm not sure that's what you are saying.

**Comment by msaraiva** [comment] 2019-12-31 01:03
> When you say dropping support for `Surface.Component`, does that mean dropping support for stateless components too? 

No, no, no! Sorry for the confusion. I want to keep the abstraction of the stateless component, however, if we change the abstraction to be on top of `Phoenix.LiveComponent`, that means it will be "stateless" from the user perspective but internally it will require a parent live view to work. I'm not sure yet how confusing this could be to newcomers, after all, functional stateless components should act just like pure functions. Live components don't work exactly like that, so I'll have to at least stop calling them **functional** ;)

> Because we use stateless components as much as possible as they are easier to use and test.

Indeed. Stateless, functional, side-effect-free will always be preferable. That's why I was so reluctant to drop the idea of a real pure functional component. However, I believe for now it's the best choice we have. If in the future people start asking for them because they want to use them without LV (which makes sense IMO) we can try again to convince the Phoenix Core Team to implement it in Phoenix itself.

**Comment by msaraiva** [comment] 2019-12-31 18:27
Hi folks! I have an update on this one.

I spoke with José earlier today about this issue. It looks there are two ways to fix this:

  1. Change the engine in Phoenix LV to support anonymous functions defined outside the `live_component/3` call.
  2. Change the Surface translator so it generates code that passes all anonymous functions directly as options to the `live_component/3` call.

Since it might take a while to have option 1 done, I started working on option 2 already. The good news is that we'll be able to keep the current behaviour of the functional stateless component 😉

**Comment by msaraiva** [comment] 2020-01-15 20:33
Hi everyone!

As explained in this [post](https://elixirforum.com/t/surface-a-component-based-library-for-phoenix-liveview/27671/29?u=msaraiva) on ElixirForum, I'm dropping support for functional non-LV components until we have a definitive solution on the Phoenix/LiveView side. So in order to be able to nest stateful components, the only feasible solution right now is to make the stateless `Surface.Component` rely on `live_component` too. This brings some immediate breaking changes:

1. **`@inner_content` has been renamed to `@content`** -  Internally all components contents (including DataComponent's) have to use LV's built-in `@inner_content` function to make nested stateful components work properly. So in order to avoid conflicts, surface's `@inner_content.()` has been renamed to `@content.()`. The same applies to data components, e.g. `col.content(...)`.

2. **Wrong errors/warnings lines for failing properties definitions of `DataComponent`** - they will always point to the line of the parent component. This will be fixed in https://github.com/msaraiva/surface/issues/15

3. **Cannot use components inside layouts** - since components now use `live_component`, you can’t use them in layouts anymore, however, you can still use the `~H` if you want to keep writing code using the Surface syntax in your layouts.

4. **wrapper components around functions must use ~H (or ~L)**  - This includes all form helpers like `text_input` and friends. Example:

    this will no longer work:

    ```elixir
    def render(assigns) do
      Phoenix.HTML.Link.link(assigns.label, to: '#', ...)
    end
    ```

    instead, you need to:

    ```elixir
    def render(assigns) do
      ~H"""
      {{ Phoenix.HTML.Link.link(assigns.label, to: '#', ...) }}
      """
    end
    ```
If you need nested stateful component and want to give it a try as soon as possible, just set up your project to use this branch https://github.com/msaraiva/surface/tree/ms-fix-inner-content. I'll only marge it in a couple of days after a few more tests.

**Comment by msaraiva** [comment] 2020-01-22 23:02
I talked to José earlier today and he told me that we can keep `inner_content` as it is and there will be no conflict. This is good news since we can keep compatibility with LiveView. That means I'm reverting number **#&#x2060;1** and merging this to master.

**Closed** 2020-01-22 23:11 UTC
