### ISSUE TITLE
Using typed slotables causes static bits to be sent down for every event

### ISSUE THREAD

**Issue by paulstatezny** [msaraiva/surface#214] opened 2020-11-26 00:05 UTC
Thanks as always for everything you're doing with Surface! ❤️ I'm hoping to get some direction and answers about some behavior I'm seeing.

## Context

Our company has a page that showcases a plethora of generic components (tabs, pagination, cards, etc) and I noticed that I would fire an event (like submitting a form) and Phoenix would send back a 250kb payload seeming to contain (almost) the entirety of the page.

## Experiment

I started cutting code until I had a minimal example: https://github.com/paulstatezny/surface-repro

(It's a standalone Phoenix app that doesn't require a DB, so feel free to clone and run it.)

If you run the app and go to http://localhost:4000, you'll see this:

<img width="842" alt="Screen Shot 2020-11-25 at 4 53 12 PM" src="https://user-images.githubusercontent.com/4662353/100292782-b66ce600-2f3e-11eb-8087-db6c5f570692.png">

The navigation tabs at the top are dynamic; you can click on them and it changes which one is highlighted.

Note the LiveView and Surface component here:

https://github.com/paulstatezny/surface-repro/blob/master/lib/surface_repro_web/live/surface_live.ex
https://github.com/paulstatezny/surface-repro/blob/master/lib/surface_repro_web/live/tabs.ex

There are links to pages with a "vanilla" LiveView version (no Surface) and another Surface version that doesn't use typed slotables.

## Observed Behavior

Turns out, if you generate code with typed slotables then every time an event happens Phoenix regenerates all of the static bits and sends them over the wire. (See the `"s"` key below.)

```json
 {
    "0":" phx-click=\"tab_changed\"",
    "1":" phx-value-key=\"team\"",
    "2":" class=\"ml-8 first:ml-0 py-4 px-1 border-b-2 text-red-600 border-red-500 bg-red-100\"",
    "3":"My Team",
    "s":[
       "<button",
       " type=\"button\"",
       "",
       ">\n  <span>",
       "</span>\n</button>\n"
    ]
 }
```

This can result in payloads that are much larger.

From the "vanilla" LiveView, containing only dynamic bits:

<img width="381" alt="Screen Shot 2020-11-25 at 4 51 26 PM" src="https://user-images.githubusercontent.com/4662353/100292944-532f8380-2f3f-11eb-9914-d3633041367a.png">

From the Surface example:

<img width="393" alt="Screen Shot 2020-11-25 at 4 51 47 PM" src="https://user-images.githubusercontent.com/4662353/100292963-604c7280-2f3f-11eb-8ef1-a5652a6e0145.png">

Not a big deal at "example scale", but our "real world" example sent 250kb payloads for every event. Not ideal.

You can view websocket payloads from each example here: https://github.com/paulstatezny/surface-repro/issues/1

## Conclusion

Are typed slotables intended to act this way? It seems if this is accepted behavior they should be avoided.

**Comment by msaraiva** [comment] 2020-11-26 12:09
Hey @paulstatezny!

Thank you so much for the detailed report and for isolating the problem on a separate project. I'll clone it and try to track the root of the problem.

**Comment by msaraiva** [comment] 2020-11-26 13:51
@paulstatezny after a few tests I was able to simulate the problem using vanilla LiveView. Is seems the problem is related to the `live_component` function itself, which is used under the hood by Surface. If you change your vanilla example to:

```elixir
defmodule SurfaceReproWeb.Tab do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~L"""
    <button type="button" phx-click="<%= @click %>" phx-value-key="<%= @key %>" class="<%= class(@selected == @key) %>">
      <span><%= @label %></span>
    </button>
    """
  end

  @base_classes "ml-8 first:ml-0 py-4 px-1 border-b-2 "

  defp class(true = _selected), do: @base_classes <> "text-red-600 border-red-500 bg-red-100"
  defp class(false = _selected), do: @base_classes <> "text-gray-500 border-transparent hover:border-gray-300"
end

defmodule SurfaceReproWeb.TabsVanilla do
  use Phoenix.LiveComponent

  def render(assigns) do
    ~L"""
    <div class="border-b border-gray-200">
      <nav class="flex -mb-px">
        <%= for {key, label} <- @tabs do %>
          <%= live_component(@socket, SurfaceReproWeb.Tab, click: @click, key: key, label: label, selected: @selected) %>
        <% end %>
      </nav>
    </div>
    """
  end
end
```

you'll see that it sends `["<button type="button" phx-click="", "" phx-value-key="", "" class="", "">↵ <span>",…]` the same way.

Please, let me know you can confirm that. If so, we'll need to report to the Phoenix LIveView team to make sure this is the expected behaviour or if it's a bug.

**Comment by msaraiva** [comment] 2020-11-26 14:03
BTW, if you convert the component into a live component (by adding an id to it) like:

```elixir
<%= live_component(@socket, SurfaceReproWeb.Tab, id: key, click: @click, key: key, label: label, selected: @selected) %>
```

the response size gets much smaller: **532bytes**. 

More interesting is that if you do the same thing in **Surface**, like:

```elixir
  defmodule InternalTab do
    use Surface.LiveComponent # LiveComponent will require an id
   ...
  end
```
and

```elixir
<InternalTab
  id={{ tab.key }}
  :for={{ tab <- @tabs }}
  click={{ @click }}
  key={{ tab.key }}
  label={{ tab.label }}
  selected={{ @selected == tab.key }}
/>
```

The response get even smaller: **345bytes**.

**Comment by msaraiva** [comment] 2020-11-26 14:18
Ok. I just confirmed that this is the expected behaviour when using `live_component`. If it's stateless (no id), it always sends the static parts.

**Comment by msaraiva** [comment] 2020-11-27 17:11
@paulstatezny I'm closing this as it's the expected behaviour for `live_component`.

BTW, were you able to find a workaround? Is converting some of the components into stateful components a feasible solution for your case?

**Closed by msaraiva** 2020-11-27 17:11 UTC

**Comment by paulstatezny** [comment] 2020-11-27 20:09
@msaraiva It turns out:

- Converting components to `Surace.LiveComponent`s and then providing `id`s _does_ make the websocket payloads more lightweight.
- But then you're forced to sprinkle `id`s all over the place.
- Most importantly: **Our use case explicitly violates the recommendations of the LiveView docs.**
    - "You should also avoid using stateful components to provide abstract DOM components." - [the docs](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveComponent.html#module-cost-of-stateful-components)
- The docs recommend using _functions_, not `LiveComponent`s to do this.

This leaves us a bit stuck between a rock and a hard place. How do we do with Surface in a way that's friendly to LiveView?

**Comment by msaraiva** [comment] 2020-11-27 21:45
> Should Surface be considering using functions under the hood instead of `LiveComponent`s in certain cases?

@paulstatezny I'd certainly consider but first we need to confirm that assumption. Have you tried using functions instead of `live_component` in your vanilla LV? I'm not sure it will make any difference regarding the payload. I believe a function may be considered as stateless, consequently the static bits might be sent too. I hope it works. This way we have a fairly easy solution to this problem.

**Comment by msaraiva** [comment] 2020-12-03 15:06
@paulstatezny do you have any updates on this? I'm curious if converting the components you have to functions would improve anything. If you want to create a separate private project (in case you can't make it public) containing only that big LV you have, I'd be glad to take a look and run some experiments to see what we can do about it.

Cheers.

**Comment by paulstatezny** [comment] 2020-12-07 21:18
@msaraiva Sorry for the radio silence!

Regarding using functions: I modified the Vanilla LiveView example to use functions in place of live components. [Here are the results.](https://github.com/paulstatezny/surface-repro/issues/1#issuecomment-740182586) As you can see, static content is pushed down the wire on each event.

As the data in that issue suggests, using a prop instead of typed slotables to pass in lists of maps is a painless way around the problem.

---

On a separate note, we did some experimentation with converting our `Surface.Component`s into `Surface.LiveComponents` to make the websocket payloads smaller. The payloads did shrink, but at the cost of bloating the memory footprint on the server. It seems like abusing stateful components is not a scalable solution, unless either (1) you won't have a large amount of concurrent users or (2) money isn't an object and you can rent servers with a lot of RAM. 😄 (RAM needs would be directly connected to your application design, of course.)

**Comment by paulstatezny** [comment] 2020-12-07 21:23
Thanks for the offer to look at our code!

If necessary, we can look down that road. But I think the facts are pretty clear. With LiveView, any markup that isn't 100% static HTML gets sent over the wire any time an event happens. Even if it hasn't changed.

This means that by the nature of LiveView, any page that is designed to hold a lot of content, with frequent Phoenix events (`handle_event`s) will simply cause lots of redundant data to be sent over the wire frequently.

Our team finds that unoptimal. (It'd be great if LiveView can detect that some section of markup hasn't changed, so don't send that section over the wire!) Nevertheless, we want to experiment with building out some real apps and getting them in production. That'll reveal if this is even a problem in practice. After all, if the payload is only 35kb or something, is it really that big of a deal?

**Comment by paulstatezny** [comment] 2020-12-07 21:32
Oh! And here are the LiveView and associated functions for reference:

https://github.com/paulstatezny/surface-repro/blob/master/lib/surface_repro_web/live/vanilla_functions_live.ex
https://github.com/paulstatezny/surface-repro/blob/master/lib/surface_repro_web/live/tabs_vanilla_functions.ex
