### ISSUE TITLE
Investigate a :slot directive to avoid template tag

### ISSUE THREAD

**Issue by Malian** [msaraiva/surface#212] opened 2020-11-21 15:05 UTC
I am playing with Surface and slots for few days now and I encountered many times the following type of repetitive code where I set several slots.

```html
      <Card>
        <template slot="header">
          <CardHeader title="A simple card header" />
        </template>

        This example demonstrates how to create components with multiple slots.
        It defines a <strong>default</strong> slot to hold the card's content
        and two <strong>named slots</strong>: header and footer.

        <template slot="footer">
          <CardFooter items={{ [{"link 1", "to1"}, {"link2", "to2"}] }} />
        </template>
      </Card>
```

I tried to fix this with "Typed Slotables" but it seems that the "Slotable" components are simple container without a `render(assigns)` function.

I am wondering if we could add a  `:slot` directive to a component to avoid the `template` tag and reduce boilerplate code.

```html
      <Card>
        <CardHeader title="A simple card header" :slot="header" />

        This example demonstrates how to create components with multiple slots.
        It defines a <strong>default</strong> slot to hold the card's content
        and two <strong>named slots</strong>: header and footer.

        <CardFooter items={{ [{"link 1", "to1"}, {"link2", "to2"}] }} :slot="footer" />
      </Card>
```

Am not sure if it's feasible neither useful, so I am asking your point of view about the proposition or any other alternative.

**Comment by msaraiva** [comment] 2020-11-23 18:48
Hi @Malian!

Although a `:slot` directive might turn out to be useful for some rare scenarios, I don't think you need it for this specific case. Could you share the code of `CardHeader` and `CardFooter`? If not, can you tell me why the code you have there is not in the `Card` component?

**Comment by Malian** [comment] 2020-11-24 14:44
The card was an example but I have a concrete case below.

First I have a "PageTitle" component that accepts a "page_title" prop and a "right" slot.
```elixir
defmodule AppWeb.Admin.Layout.PageTitle do
  use AppWeb, :surface_component

  prop page_title, :string, required: true

  @doc "A slot that is pushed on the right of the title"
  slot actions

  def render(assigns) do
    ~H"""
      <div class="border-b border-gray-200 px-4 py-4 flex items-center justify-between sm:px-6 lg:px-8">
        <div class="flex-1 min-w-0 py-2">
          <h1 class="text-lg font-medium leading-6 text-gray-900 sm:truncate">
            {{ @page_title }}
          </h1>
        </div>
        <div class="flex" :if={{ slot_assigned?(:actions) }}>
          <slot name="actions"/>
        </div>
      </div>
    """
  end
end
```
I use it in my LiveView like this:
```html
<Layout>
  <PageTitle page_title={{ @presentation_model.page_title }}>
    <template slot="actions">
      <LiveRedirect to={{ @presentation_model.new_path.(@socket)}} class="inline-flex items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-purple-600 hover:bg-purple-500 focus:outline-none focus:shadow-outline-purple focus:border-purple-700 active:bg-indigo-700 transition duration-150 ease-in-out">
        New Vehicle
      </LiveRedirect>
    </template>
  </PageTitle>
</Layout>
```

In this case I could use the default slot to remove the template tag.

Why is the code I have not in the `Card` component? Because I could have several type of `CardHeader` for example. The general design of the cards is always the same but the header can change depending on the context. For example, I use these cards from Tailwindui: https://tailwindui.com/components/application-ui/headings/card-headings I could generate a "Card" or a "CardHeader" component that manages all the different headers.

Maybe I am overengineering my templates :wink: 

The ideal case I imagine is to be able to use the `CardHeader` and the `CardFooter` without the `:slot` directive in the template but like the `slotable` component.

```elixir
defmodule Card do
  use AppWeb, :surface_component

  slot header
  slot default
  slot footer

  def render(assigns) do
    ~H"""
      <div>
        <slot name="header">
        <slot />
        <slot name="footer">
      </div>
    """
  end
end

defmodule CardHeader do
  use AppWeb, :surface_component, slot: "header"

  prop title, :string, required: true

  def render(assigns) do
    ~H"""
      <div>
         {{ title }}
      </div>
    """
  end
end
```
```html
<Card>
  <CardHeader title="My Title" />
  My Body
</Card>
```
And the result will be:
```html
<div>
  <div>My Title</div>
  MyBody
</div>
```

Moreover, using the component like this
```html
<Card>
  My Body
  <CardHeader title="My Title" />
</Card>
```
Will result in the same html output.

Maybe I am misunderstanding the way we should use Surface and maybe I am creating to much component ^^

**Comment by msaraiva** [comment] 2020-11-24 21:20
> Why is the code I have not in the `Card` component? Because I could have several type of `CardHeader` for example.

I see what you mean now. The problem is how to introduce such a feature without making the whole slot thing confusing. 

Currently, renderless components can be treated as templates because they work similarly, i.e., they both act as information holders that can be passed to the parent component. The basic difference is that while templates can only hold and pass a code block, renderless components can additionally hold and pass properties. However, none of them is responsible for rendering anything. The parent is always responsible for the rendering. This is nice because it imposes a clear distinction about where are all the information that is passed (at the caller's site) and where that information will be used and eventually rendered (inside the callee's `render/1` function).

Now, if we allow passing regular components as templates, we add a second place that will also be responsible for the rendering. To make it worse, both places may add logic and conditionally render things based on the same set of passed properties, which will be available for both. I believe this can be extremely confusing when it comes to reasoning about the rendering behaviour. Additionally, it might be a nightmare to make it work with contexts as well.

@lnr0626 I'd love to hear your thoughts on this one. It sounds like a nice feature but I'm not sure it will play nice with the existing model. I might be wrong though :)

@Malian do you know how this can be achieved using other frameworks?

**Comment by lnr0626** [comment] 2020-11-25 01:53
Adding a new directive (if we were to implement this, it should probably be namd `:template` instead of `:slot`) that'd just remove the boilerplate for simple cases would be fairly straightforward - i.e. it could just wrap the node in a template ast node:

```
<MyComponent :template="header" />
```
would transform into:
```
<template name="header">
  <MyComponent />
</template>
```

That somewhat mirrors the `:if`/`:for` directives and the recent `If`/`For` constructs we've added, so doesn't feel foreign to me. However, we'd have to decide if we wanted to support using `:let` with that directive (and if so, how that would work); and what types of things we'd want to support using this directive on (i.e. it probably makes sense for tags/void tags/components, but probably doesn't make sense for slottable components/the slot element/the template element).

Potential points of confusion:
* directive ordering - if i specify all of [`:template`, `:for`, and `:if`], what order would they apply in?
* slottable components and normal components look very similar; why can i use this on one component, but not another
* `:let` has a few complications that come to mind: `<MyComponent :template="header" :let={{ prop: value }} />` is `:let` for the `:template` directive, or is it for the default slot in `MyComponent`

---

@Malian I've not had a need for their cards yet in my app, but for other similar components I've done something along the lines of:

```
defmodule App.Card.LinkAction do
    use Surface.Component, slot: "action"
    prop label, :string
    prop href, :string
end

defmodule App.Card.ButtonAction do
    use Surface.Component, slot: "action"
    prop label, :string
    prop event, :event
end

defmodule App.Card do
    use Surface.Component

    prop title, :string, required: true
    prop description, :string
    prop avatar, 

    def render(assigns) do
        ~H"""
        <div>
            <header>
                <div>
                    <div :if={{ @avatar }}>
                        <!-- render avatar -->
                    </div>
                    <div>
                        <div :if={{ @title }}>
                            <!-- render title -->
                        </div>
                        <div :if={{ @description }}>
                            <!-- render description -->
                        </div>
                    </div>
                </div>
                <div>
                    <div :for.with_index={{ action <- @action }}>
                        <!-- render action using LiveRedirect/LivePatch/button with @click/etc. -->
                        <LiveRedirect :if={{ action[:href] }} to={{ action.href }}>
                           <slot name="action" index={{ i }}>{{ action.label }}</slot>
                        </LiveRedirect>
                        <button :if={{ action[:event] }} :on-click={{ action.event }}>
                           <slot name="action" index={{ i }}>{{ action.label }}</slot>
                        </button>
                    </div>
                </div>
            </header>
            <!-- card styling/markup/etc. -->
        </div>
        """
    end
end
```

and then using it like so:
```
<App.Card title="Job Postings" description="Lorem ipsum dolor sit amet consectetur adipisicing elit quam corrupti consectetur" />
    <App.Card.ButtonAction label="Create new job" event="create" />
    <App.Card.LinkAction href="#>
        <Icon name="phone">
         Phone
    </App.Card.LinkAction>
    
    <!-- card contents -->
</App.Card>
```

You end up with a bit of extra markup occasionally, but it doesn't seem to affect the final look. It's worked fairly well for what I've needed so far. The different variants that tailwind ui offers seem to follow a similar pattern where each one has pretty similar markup and can usually be generalized.

**Comment by Malian** [comment] 2020-12-11 08:00
Thank you both for your detailed answers and sorry for my late response!

@lnr0626 solution fits my needs so I will go further with it.

Another case that comes in my mind where this feature could be useful is a "layout" system but it is not really clear right now :smiley:  I'm going to let this idea mature!

I'll let you close the issue if it's ok with you.

**Comment by msaraiva** [comment] 2020-12-11 13:02
@Malian yeah, you can close it for now but feel free to reopen it anytime you have new related information or ideas. A "layout' system is something I'm very interested in. Let me know when you have something to share. Cheers.

**Closed** 2020-12-11 16:24 UTC
